version: '3.8'
name: one-on-one
volumes:
    one-on-one-db-data:
        driver: local
services:
  php:
    container_name: one-php
    image: hyperf/hyperf:8.3-alpine-v3.19-swoole
    volumes:
      - ./:/opt/www
    ports:
      - "9510:9501"
    working_dir: /opt/www
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    entrypoint: ["sh", "-c", "composer install && php /opt/www/bin/hyperf.php server:watch"]
  db:
    container_name: one-db
    image: mysql:latest
    volumes:
      - one-on-one-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: one-on-one
      MYSQL_TCP_PORT: 3331
    ports:
      - "3331:3331"

networks:
  default:
    name: one-on-one
